GET http://localhost:3000/user/
content-type: application/json

#######

POST http://localhost:3000/user/create
content-type: application/json

{
    "email": "johndoe@me.com",
    "password": "password"
}

######

post http://localhost:3000/user/login
content-type: application/json

{
    "email": "johndoe@me.com",
    "password": "password"
}
